server:
  port: 7002
spring:
  datasource:
    url: jdbc:mysql://121.199.73.186:3306/SpringCloudStudy?useUnicode=true&characterEncoding=utf-8&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: xxjjss123321
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
eureka:
  instance:
    hostname: eureka7002
  #这个是euraka暴漏给提供者和消费者服务发现注册用的
  client:
    service-url:
      defaultZone: http://eureka7001:7001/eureka/
    #是否注册到eureka上注册中心是不用把自己上床到自己的provider
    register-with-eureka: false
    #是否需要到eureka上拉去服务路径--consumer需要
    fetch-registry: false
