server:
  port: 8001

spring:
  application:
    name: cloud-provider-hystrix-payment
  datasource:
    url: jdbc:mysql://121.199.73.186:3306/SpringCloudStudy?useUnicode=true&characterEncoding=utf-8&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: xxjjss123321
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
#      单机版：hystrix
       defaultZone: http://eureka7001:7001/eureka
#      defaultZone: http://eureka7001:7001/eureka,http://eureka7002:7002/eureka 集群版
  instance:
    instance-id: payment8001
    prefer-ip-address: true
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.Jason.entity